name: Formula CI
# this workflow will
# - run formula validation step - test/validate-formula.sh
# - deliver the package content to the configured repository
# - submit the new package content to the upstream repository
on: [push, pull_request]
env:
  PACKAGE_NAME: saphanabootstrap-formula 
jobs:

  validation:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Add salt repository
      uses: myci-actions/add-deb-repo@4
      with:
        repo: deb http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest/ bionic main
        key-server: http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest/SALTSTACK-GPG-KEY.pub
    - name: install salt
      run: sudo apt-get install salt-common
    - name: validation script
      run: ci/validate-formula.sh

  delivery:
    needs: validation
    runs-on: ubuntu-18.04
    if: ${{ github.event_name != 'pull_request' }}  
    container: 
      image: shap/continuous_deliver
      env:
        OBS_USER: ${{ secrets.OBS_USER }}
        OBS_PASS: ${{ secrets.OBS_PASS }}
        OBS_PROJECT: ${{ secrets.OBS_PROJECT }}
    steps:
    - uses: actions/checkout@v2 
      with:
        fetch-depth: 0
    - name: configure OSC  
    # OSC credentials must be configured beforehand as the HOME variables cannot be changed from /github/home
    # that is used to run osc commands 
      run: | 
        /scripts/init_osc_creds.sh
        mkdir -p $HOME/.config/osc
        cp /root/.config/osc/oscrc $HOME/.config/osc
    - name: deliver package
      run: |
        sed -i 's~%%VERSION%%~${{ github.sha }}~' _service && \
        sed -i 's~%%REPOSITORY%%~${{ github.repository }}~' _service && \
        /scripts/upload.sh 

  submit:
    needs: [validation, delivery]
    runs-on: ubuntu-18.04
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}    
    container:
      image: shap/continuous_deliver
      env:
        OBS_USER: ${{ secrets.OBS_USER }}
        OBS_PASS: ${{ secrets.OBS_PASS }}
        OBS_PROJECT: ${{ secrets.OBS_PROJECT}}
        TARGET_PROJECT: ${{ secrets.TARGET_PROJECT}}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: configure OSC
      run: | 
        /scripts/init_osc_creds.sh
        mkdir -p $HOME/.config/osc
        cp /root/.config/osc/oscrc $HOME/.config/osc
    - name: submit package
      run: |
       sed -i 's~%%VERSION%%~${{ github.sha }}~' _service && \
       sed -i 's~%%REPOSITORY%%~${{ github.repository }}~' _service && \
       /scripts/submit.sh
